name: Test validate.py
on: [push]

jobs:
  yaml-schema-validation:
    strategy:
      matrix:
        yamale: ["2.0.0", "3.0.0", "4.0.0"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build docker image
      run: docker build -t local .
    - name: Run docker image
      run: docker run -e INPUT_YAMALE='${{ matrix.yamale }}' -e INPUT_VALIDATORS_REQUIREMENTS='example/requirements.txt' -e INPUT_SCHEMA='example/attribution_schema.yml' -e INPUT_PATH_PATTERN='example/.+_file\.yml$' -e INPUT_VALIDATORS_PATH='example/validators.py' local
