name: Test validate.py
on: [push]

jobs:
  yaml-schema-validation:
    strategy:
      matrix:
        yamale: ["3.0.0", "4.0.0"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build docker image
      run: docker build -t local .
    - name: test valid file
      run: docker run -e INPUT_YAMALE='${{ matrix.yamale }}' -e INPUT_VALIDATORS_REQUIREMENTS='example/requirements.txt' -e INPUT_SCHEMA='example/attribution_schema.yml' -e INPUT_PATH_PATTERN='.*example/valid_file\.yml$' -e INPUT_VALIDATORS_PATH='example/validators.py' local
    - name: test invalid file
      continue-on-error: true
      run: docker run -e INPUT_YAMALE='${{ matrix.yamale }}' -e INPUT_VALIDATORS_REQUIREMENTS='example/requirements.txt' -e INPUT_SCHEMA='example/attribution_schema.yml' -e INPUT_PATH_PATTERN='.*example/invalid_file\.yml$' -e INPUT_VALIDATORS_PATH='example/validators.py' local
    - name: invalid file did not error out
      if: ${{ steps.commitlint.outcome == 'success' }}
      run: exit 1

