name: Test validate.py
on: [push]

jobs:
  yaml-schema-validation:
    strategy:
      matrix:
        yamale: [1.0, 2.0, 3.0, 4.0]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - env:
        INPUT_YAMALE: ${{ matrix.yamale }}
        INPUT_VALIDATORS_REQUIREMENTS: example/requirements.txt
      run: |
        chmod +x entrypoint.sh
        ./entrypoint.sh
    - run: python3 validate.yml
      env:
        INPUT_SCHEMA: example/attribution_schema.yml
        INPUT_PATH_PATTERN: example/.+_file\.yml$
        INPUT_VALIDATORS_PATH: example/validators.py
